// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqjH21-BxXIlAQ8WVAvu566_KHgWWyA2Q',
    appId: '1:1069484521712:web:935a89d4b66b6951256a35',
    messagingSenderId: '1069484521712',
    projectId: 'codexia-e-learning',
    authDomain: 'codexia-e-learning.firebaseapp.com',
    databaseURL: 'https://codexia-e-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codexia-e-learning.appspot.com',
    measurementId: 'G-VTNKYXTG4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_I4uDhwwiZfJRX2fs_HuQGoAqlRiRnQ',
    appId: '1:1069484521712:android:2daf1201e2cf9262256a35',
    messagingSenderId: '1069484521712',
    projectId: 'codexia-e-learning',
    databaseURL: 'https://codexia-e-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codexia-e-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTH4JHdewrjr9P1VNgsQtUJ3M8m23uwAQ',
    appId: '1:1069484521712:ios:5e52e08f44c77943256a35',
    messagingSenderId: '1069484521712',
    projectId: 'codexia-e-learning',
    databaseURL: 'https://codexia-e-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codexia-e-learning.appspot.com',
    androidClientId: '1069484521712-0d8ivk310cfmcqhifri7m6cvolacmbcm.apps.googleusercontent.com',
    iosClientId: '1069484521712-q37rfqqpqilqn1t3q5dtui90l1kuie1p.apps.googleusercontent.com',
    iosBundleId: 'com.codexia.codexiaELearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTH4JHdewrjr9P1VNgsQtUJ3M8m23uwAQ',
    appId: '1:1069484521712:ios:143856f47d99c925256a35',
    messagingSenderId: '1069484521712',
    projectId: 'codexia-e-learning',
    databaseURL: 'https://codexia-e-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codexia-e-learning.appspot.com',
    androidClientId: '1069484521712-0d8ivk310cfmcqhifri7m6cvolacmbcm.apps.googleusercontent.com',
    iosClientId: '1069484521712-0jnk8dp5s8q6d20k21f6gsmdpoqtrdq4.apps.googleusercontent.com',
    iosBundleId: 'com.codexia.codexiaELearning.RunnerTests',
  );
}
