// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV4wgAv_eaOQHOzRJO6NNMziudCAvFmOM',
    appId: '1:799694197291:web:0978aa6be7d7bc4122506e',
    messagingSenderId: '799694197291',
    projectId: 'admin-e-learning-a7fdd',
    authDomain: 'admin-e-learning-a7fdd.firebaseapp.com',
    databaseURL: 'https://admin-e-learning-a7fdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-e-learning-a7fdd.appspot.com',
    measurementId: 'G-KETMQHZFNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfN2mLeA5rFehzotzOVBTTE-xf2MOExu0',
    appId: '1:799694197291:android:46f4b41d8ce9ddb122506e',
    messagingSenderId: '799694197291',
    projectId: 'admin-e-learning-a7fdd',
    databaseURL: 'https://admin-e-learning-a7fdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-e-learning-a7fdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAdJVcoCloSumlTQViXhgh_vfoqsSq7I8',
    appId: '1:799694197291:ios:0d3bbeabd190425c22506e',
    messagingSenderId: '799694197291',
    projectId: 'admin-e-learning-a7fdd',
    databaseURL: 'https://admin-e-learning-a7fdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-e-learning-a7fdd.appspot.com',
    iosBundleId: 'com.codexia.codexiaELearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAdJVcoCloSumlTQViXhgh_vfoqsSq7I8',
    appId: '1:799694197291:ios:ec06fa190c64fbd222506e',
    messagingSenderId: '799694197291',
    projectId: 'admin-e-learning-a7fdd',
    databaseURL: 'https://admin-e-learning-a7fdd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'admin-e-learning-a7fdd.appspot.com',
    iosBundleId: 'com.codexia.codexiaELearning.RunnerTests',
  );
}
